### ISSUE TITLE
I can't log in normally

### ISSUE THREAD

**Issue by yuexuanblog** [577fkj/GenshinProxy#1]
我登录的时候会提示连接超时,不知道怎么办才好
When I log in, I will be prompted that the connection times out. I don't know what to do
![Screenshot_2022-05-13-14-15-37-182_com miHoYo Gen](https://user-images.githubusercontent.com/89347877/168231581-00d6eb9f-c498-49ec-abbc-43fd3b609a91.jpg)

**Comment by 577fkj** [comment]
请确保你浏览器能打开Grasscutter的界面

**Comment by yuexuanblog** [comment]
> 请确保你浏览器能够打开 Grasscutter 的界面
请问"Grasscutter 的界面"是指什么呢?

**Comment by 577fkj** [comment]
> > 请确保你浏览器能够打开 Grasscutter 的界面
> > 请问"Grasscutter 的界面"是指什么呢?

最新版已无需这样操作

**Comment by yuexuanblog** [comment]
> > > 请确保你浏览器能够打开 Grasscutter 的界面问
> > > “Grasscutter 的界面”是指手指吗？
> 
> 最新版已独立操作
好的,感谢您,我会马上尝试.

**Comment by yuexuanblog** [comment]
> > > 请确保你浏览器能够打开 Grasscutter 的界面问
> > > “Grasscutter 的界面”是指手指吗？
> 
> 最新版已独立操作

我还是无法登录到私人服务器,请问需要安装CA证书吗?或者可以有一个教程吗?

**Comment by 577fkj** [comment]
> 

有没有什么错误提示

**Comment by yuexuanblog** [comment]
> > 
> 
> 有没有什么错误提示

没有，它就这样一直转着，同时PC客户端是可以正常登录的
![Screenshot_2022-05-14-19-12-33-563_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168423406-b8f7445b-62c7-4891-ab39-3c3b5b677b6d.jpg)

**Comment by 577fkj** [comment]
> > > 
> > 
> > 
> > 有没有什么错误提示
> 
> 没有，它就这样一直转着，同时PC客户端是可以正常登录的 ![Screenshot_2022-05-14-19-12-33-563_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168423406-b8f7445b-62c7-4891-ab39-3c3b5b677b6d.jpg)

accessAddress你填写的什么

**Comment by yuexuanblog** [comment]
> > > > 
> > > 
> > > 
> > > 有没有什么错误提示
> > 
> > 没有，它就这样一直转着，同时PC客户端是可以正常登录的 ![Screenshot_2022-05-14-19-12-33-563_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168423406-b8f7445b-62c7-4891-ab39-3c3b5b677b6d.jpg)
> 
> accessAddress你填写的什么

![Screenshot_2022-05-14-21-53-39-978_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168428842-8fc95b61-45f8-4c6b-8b50-8825c48af6cd.jpg)
是指这个吗？填写的服务器IP和代理端口

**Comment by 577fkj** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 有没有什么错误提示
> > > 
> > > 
> > > 没有，它就这样一直转着，同时PC客户端是可以正常登录的 ![Screenshot_2022-05-14-19-12-33-563_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168423406-b8f7445b-62c7-4891-ab39-3c3b5b677b6d.jpg)
> > 
> > 
> > accessAddress你填写的什么
> 
> ![Screenshot_2022-05-14-21-53-39-978_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168428842-8fc95b61-45f8-4c6b-8b50-8825c48af6cd.jpg) 是指这个吗？填写的服务器IP和代理端口

请不要输入代理端口 直接输入服务器端口

**Comment by yuexuanblog** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 有没有什么错误提示
> > > > 
> > > > 
> > > > 没有，它就这样一直转着，同时PC客户端是可以正常登录的 ![Screenshot_2022-05-14-19-12-33-563_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168423406-b8f7445b-62c7-4891-ab39-3c3b5b677b6d.jpg)
> > > 
> > > 
> > > accessAddress你填写的什么
> > 
> > ![Screenshot_2022-05-14-21-53-39-978_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168428842-8fc95b61-45f8-4c6b-8b50-8825c48af6cd.jpg) 是指这个吗？填写的服务器IP和代理端口
> 
> 请不要输入代理端口 直接输入服务器端口

我改成config.json中默认的22102端口会报网络错误
但是我直接在wifi处设置代理就可以直接登录

**Comment by 577fkj** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 有没有什么错误提示
> > > > > 
> > > > > 
> > > > > 没有，它就这样一直转着，同时PC客户端是可以正常登录的 ![Screenshot_2022-05-14-19-12-33-563_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168423406-b8f7445b-62c7-4891-ab39-3c3b5b677b6d.jpg)
> > > > 
> > > > 
> > > > accessAddress你填写的什么
> > > 
> > > 
> > > ![Screenshot_2022-05-14-21-53-39-978_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168428842-8fc95b61-45f8-4c6b-8b50-8825c48af6cd.jpg) 是指这个吗？填写的服务器IP和代理端口
> > 
> > 
> > 请不要输入代理端口 直接输入服务器端口
> 
> 我改成config.json中默认的22102端口会报网络错误 但是我直接在wifi处设置代理就可以直接登录

不要填写游戏端口 填写display端口

**Comment by yuexuanblog** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 有没有什么错误提示
> > > > > > 
> > > > > > 
> > > > > > 没有，它就这样一直转着，同时PC客户端是可以正常登录的 ![Screenshot_2022-05-14-19-12-33-563_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168423406-b8f7445b-62c7-4891-ab39-3c3b5b677b6d.jpg)
> > > > > 
> > > > > 
> > > > > accessAddress你填写的什么
> > > > 
> > > > 
> > > > ![Screenshot_2022-05-14-21-53-39-978_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/89347877/168428842-8fc95b61-45f8-4c6b-8b50-8825c48af6cd.jpg) 是指这个吗？填写的服务器IP和代理端口
> > > 
> > > 
> > > 请不要输入代理端口 直接输入服务器端口
> > 
> > 
> > 我改成config.json中默认的22102端口会报网络错误 但是我直接在wifi处设置代理就可以直接登录
> 
> 不要填写游戏端口 填写display端口

非常不好意思,我并不知道display端口是什么,可以告诉我在哪里找到它吗?

**Comment by 577fkj** [comment]
![image](https://user-images.githubusercontent.com/86393520/168429585-d3ba4d28-1597-4598-8d05-89fd73ab0ccc.png)

**Comment by yuexuanblog** [comment]
> ![图片](https://user-images.githubusercontent.com/86393520/168429585-d3ba4d28-1597-4598-8d05-89fd73ab0ccc.png) 说错了应该是dispatch

我的设置如下,现在是这样的
![Uploading Screenshot_2022-05-14-22
![QQ截图20220514225129](https://user-images.githubusercontent.com/89347877/168430857-bd946125-4aed-423d-b604-b0d07b1db20c.png)
-50-28-862_com.miHoYo.Gen.jpg…]()

**Comment by yuexuanblog** [comment]
> ![图片](https://user-images.githubusercontent.com/86393520/168429585-d3ba4d28-1597-4598-8d05-89fd73ab0ccc.png) 说错了应该是dispatch

我现在的设置是这样的
![QQ截图20220514225129](https://user-images.githubusercontent.com/89347877/168430989-bf7812ed-0481-4521-8b46-0b971e0e7d2b.png)
登录时是这样的
![Screenshot_2022-05-14-22-50-28-862_com miHoYo Gen](https://user-images.githubusercontent.com/89347877/168431038-4f9709da-3b38-4f04-9782-48845656f7f5.jpg)

**Comment by 577fkj** [comment]
> > ![图片](https://user-images.githubusercontent.com/86393520/168429585-d3ba4d28-1597-4598-8d05-89fd73ab0ccc.png) 说错了应该是dispatch
> 
> 我现在的设置是这样的 ![QQ截图20220514225129](https://user-images.githubusercontent.com/89347877/168430989-bf7812ed-0481-4521-8b46-0b971e0e7d2b.png) 登录时是这样的 ![Screenshot_2022-05-14-22-50-28-862_com miHoYo Gen](https://user-images.githubusercontent.com/89347877/168431038-4f9709da-3b38-4f04-9782-48845656f7f5.jpg)

请保证你浏览器能打开那个地址

**Comment by yuexuanblog** [comment]
> > > ![图片](https://user-images.githubusercontent.com/86393520/168429585-d3ba4d28-1597-4598-8d05-89fd73ab0ccc.png)说错了应该是dispatch
> > 
> > 
> > 我的设置是这样的![QQ截图20220514225129](https://user-images.githubusercontent.com/89347877/168430989-bf7812ed-0481-4521-8b46-0b971e0e7d2b.png)登录时是现在这样的![截图_2022-05-14-22-50-28-862_com miHoYo Gen](https://user-images.githubusercontent.com/89347877/168431038-4f9709da-3b38-4f04-9782-48845656f7f5.jpg)
> 
> 请保证你的浏览器能打开那个地址
![QQ截图20220514225626](https://user-images.githubusercontent.com/89347877/168431372-6171d444-38bd-4f74-98d2-d26222df6b9c.png)

这是该地址打开时的状况,我不知道怎么处理它

**Comment by 577fkj** [comment]
> 

此软件不需要任何代理 请关掉你的代理 并使用地址直连

**Comment by yuexuanblog** [comment]
> > 
> 
> 此软件不需要任何代理 请关掉你的代理 并使用地址直连

我关闭了所有代理,使用地址直连仍然提示4206,浏览器访问该地址时会提示下载

**Comment by 577fkj** [comment]
> > > 
> > 
> > 
> > 此软件不需要任何代理 请关掉你的代理 并使用地址直连
> 
> 我关闭了所有代理,使用地址直连仍然提示4206,浏览器访问该地址时会提示下载

正常访问地址会显示这个 如果显示不正确请检查你的服务器配置
如果还是不行请开启设置里的强制模式
![image](https://user-images.githubusercontent.com/86393520/168432847-792991cf-2ddb-4180-a678-844c9df61ca4.png)

**Comment by yuexuanblog** [comment]
开启强制模式之后,出现了我的虚拟账号在官服出现这一奇怪景象,但是再开启跳过SSL证书检查之后,客户端正常登录了.非常感谢您的耐心回答.祝生活顺利,事业有成
