### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by momwoof** [577fkj/GenshinProxy#12]
Vivo X20A手机(未root)(无Xposed)在运行 [genshin-impact-308-lspatched.apk] 的时候，还没有出现mihoyo界面时自动退出
具体视频链接:https://gofile.io/d/zZxDgJ
求大佬修复ovo

**Comment by momwoof** [comment]
安卓版本8.1.0

**Comment by 577fkj** [comment]
我需要日志

**Comment by 64646494994946464949646464** [comment]
我点完进入私服后一直闪退

**Comment by 577fkj** [comment]
无root版本不支持9.0以下系统

**Comment by duzhaokun123** [comment]
@577fkj 所以你有没有改一下 minsdk 免得人装上大叫用不成

**Comment by 577fkj** [comment]
> @577fkj 所以你要不要改一下 minsdk 免得人装上大叫用不成

patch版本会自动改minsdk吗

**Comment by duzhaokun123** [comment]
> patch版本会自动改minsdk吗

显然是没有的

**Comment by 577fkj** [comment]
> > patch版本会自动改minsdk吗
> 
> 显然是没有的

🤔
