### ISSUE TITLE
脚本UI问题了

### ISSUE THREAD

**Issue by jinghuashang** [577fkj/GenshinProxy#16]
设置里面没有关闭游戏等的按键，如果强制退出游戏会黑屏，请问咋解决啊

**Comment by jinghuashang** [comment]
![1a3774028620d2.jpg](https://user-images.githubusercontent.com/77230776/173321489-b22b4458-87a7-4c0c-b55b-c8ebf4ffe3a6.jpg)

**Comment by 577fkj** [comment]
> ![1a3774028620d2.jpg](https://user-images.githubusercontent.com/77230776/173321489-b22b4458-87a7-4c0c-b55b-c8ebf4ffe3a6.jpg)

谁教你这样全选的
没有返回按钮就重启游戏直接进自定义服务器
配置自动保存的

**Comment by jinghuashang** [comment]
重启游戏黑屏啊

**Comment by 577fkj** [comment]
> 重启游戏黑屏啊

发个复现视频

**Comment by duzhaokun123** [comment]
@577fkj 看上去你没加 scrollview

**Comment by 577fkj** [comment]
> @577fkj 看上去你没加 scrollview

加了 dialog的问题下面的按钮不会滑上来

**Comment by jinghuashang** [comment]
服务器那里多打了个回车，虽然能点到，但还是没显示，不过能进游戏了

**Comment by duzhaokun123** [comment]
> > @577fkj 看上去你没加 scrollview
> 
> 加了 dialog的问题下面的按钮不会滑上来

不应该吧 是不是 mathparent 了

**Comment by Daisg1** [comment]
> > 重开游戏黑屏啊
> 
> 发个复现视频

怎么进私服啊

**Comment by 577fkj** [comment]
> > > 重开游戏黑屏啊
> > 
> > 
> > 发个复现视频
> 
> 怎么进私服啊

用手进

**Comment by Daisg1** [comment]
> > > > 重开游戏黑屏啊
> > > 
> > > 
> > > 发个复现视频
> > 
> > 怎么进私服啊
> 
> 用手进

![Screenshot_2022-06-15-10-07-57-05_e80eb31669cc7edfbce1531f4d25a535.jpg](https://user-images.githubusercontent.com/85570207/173736938-a5f9f996-6830-4cf6-bdd4-7c88ef45ed72.jpg)老哥帮帮忙

**Comment by Daisg1** [comment]
> > > > 重开游戏黑屏啊
> > > 
> > > 
> > > 发个复现视频
> > 
> > 怎么进私服啊
> 
> 用手进

我第一次玩这个
