### ISSUE TITLE
I need to make a clone of patched genshin. (Or just edit it)

### ISSUE THREAD

**Issue by ahar2611** [577fkj/GenshinProxy#17]
I want to have both normal genshin and patched genshin at the same time so i need to make a clone of patched genshin with a different name and package. Or maybe just edit the apk. Can you please help me? I can't edit the apk. (I tried) Can u make one for me, please?

**Comment by ahar2611** [comment]
我想你更喜欢用中文说话，所以我会试着翻译我上面所说的。 我想同时拥有普通和修改后的 Genshin Impact。 所以我需要其中一个具有不同的名称和包（我的意思是 com.miHoYo.GenshinImpact 文件）。 你能帮我么？

**Comment by 577fkj** [comment]
Not so far. The module is only available for com miHoYo. Genshinimpact takes effect, and I will add support later

**Comment by 577fkj** [comment]
Supported in the latest release

**Comment by qwertyuiop192** [comment]
Leave a comment

**Comment by qwertyuiop192** [comment]
qwer

**Comment by qwertyuiop192** [comment]
qwee
