### ISSUE TITLE
配置文件的位置？

### ISSUE THREAD

**Issue by 1818yu** [577fkj/GenshinProxy#19]
我无脑打开了所有的选项导致现在进不去游戏（表现为一直黑屏），我想重置下模块的设置。删除，重装模块没能解决

**Comment by 577fkj** [comment]
如果没有root 那就只能清空游戏数据

**Comment by 577fkj** [comment]
> > 
> 
> 
> 
> 我的设备已root，请问位置在？

在原神的私有目录的shared_prefs
/data/user/0/com.miHoYo.GenshinImpact/shared_prefs/serverConfig.xml
