### ISSUE TITLE
有倒卖狗，大佬

### ISSUE THREAD

**Issue by Muggles001** [577fkj/GenshinProxy#23]
点击链接加入群聊【原神公益私服】：https://jq.qq.com/?_wv=1027&k=ByTaKpiE
![-2a7131961eb0c5a3](https://user-images.githubusercontent.com/62734960/175753736-12793594-033c-467b-aa4e-1599ec5867d7.jpg)

**Comment by casksteven** [comment]
顶

**Comment by duzhaokun123** [comment]
能确定是倒卖这个吗

**Comment by 577fkj** [comment]
> 

服 我没什么好办法
