### ISSUE TITLE
大佬，可以发我源码吗，我想和我同学一起玩，我想把这东西改成特定代理

### ISSUE THREAD

**Issue by fanlepian1** [577fkj/GenshinProxy#24]
大佬，可以发我源码吗，我想和我同学一起玩，我想把这东西改成特定代理
然后实现打开就能用

**Comment by fanlepian1** [comment]
QQ:3562822362
QQ邮箱:fanlepian@foxmail.com

**Comment by 577fkj** [comment]
定制客户端请联系 https://t.me/xfk233
