### ISSUE TITLE
关于版本号问题

### ISSUE THREAD

**Issue by dahisea** [577fkj/GenshinProxy#26]
releases里是2.6，但是下载下来显示2.4，我感到十分疑惑😳😂

![Screenshot_20220701-224926_Via](https://user-images.githubusercontent.com/81472122/176918450-fb5bb468-1817-453e-b04f-2450b0cb6e69.png)

![Screenshot_20220701-225121_](https://user-images.githubusercontent.com/81472122/176918479-3199e811-2188-4847-8af5-877b48c1ba81.png)

**Comment by 577fkj** [comment]
已更新 我都没发现

**Comment by dahisea** [comment]
已解决
