### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by zshMVP** [577fkj/GenshinProxy#27]
Android12
客户端是2.7.0
xp模块是2.6
服务端好像是1.2
![Screenshot_20220705-155634_设置](https://user-images.githubusercontent.com/74349057/177279108-eac9a5a7-5463-495c-8717-d22363f66cb6.png)

**Comment by zshMVP** [comment]
[录屏](http://cdn.zshmvp.com/screen-20220705-155525.mp4)

**Comment by 577fkj** [comment]
请提供日志

**Comment by zshMVP** [comment]
[lsp日志](https://cdn.zshmvp.com/LSPosed_2022-07-05T16_37_55.845.zip)
[应用程序崩溃日志](https://www.toptal.com/developers/hastebin/raw/fiqiqafigo)

**Comment by 577fkj** [comment]
你服务器地址填错了

**Comment by ppprox** [comment]
请问服务器地址应该填什么呢
