### ISSUE TITLE
下载官服资源还需要更新客户端，但是进不去更新界面

### ISSUE THREAD

**Issue by famsonu** [577fkj/GenshinProxy#35]
能帮忙解决一下吗？

**Comment by 577fkj** [comment]
?

**Comment by famsonu** [comment]
![Screenshot_20220716_165235](https://user-images.githubusercontent.com/109411662/179347965-a17aea79-2a89-4a4c-9228-94f9416d45ce.jpg)

**Comment by famsonu** [comment]
还有这个
![Uploading Screenshot_20220716_165411.jpg…]()

**Comment by baibaishuzhi** [comment]
翻译:还有多久更新。

**Comment by famsonu** [comment]
这我也不知道

**Comment by baibaishuzhi** [comment]
已经传了？大小1.2G？

**Comment by famsonu** [comment]
大小1.09G



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月16日 17:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [577fkj/GenshinProxy] 下载官服资源还需要更新客户端，但是进不去更新界面 (Issue #35) |

已经传了？大小1.2G？

**Comment by famsonu** [comment]
![Uploading Screenshot_20220716_203221.jpg…]()
