### ISSUE TITLE
为什么会闪退

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [577fkj/GenshinProxy#37]
我通过 LSP-Patch 把3.0的APK打上了GenShinProxy模块，并且输入了我服务器地址，点击自定义服务器，在 hoyoverse 显示完后就闪退了。求求大佬
服务器地址 ：https://cloud.nat.yinidc.cn:18224

/![Screenshot_2022-08-24-13-43-34-55_e80eb31669cc7edfbce1531f4d25a535.jpg](https://user-images.githubusercontent.com/54192955/186340547-09dc12cb-7443-461a-991d-8c5661a03cb3.jpg)

**Comment by 577fkj** [comment]
为什么你觉得他支持3.0

**Comment by ErrorCodesForLzx** [comment]
> 为什么你觉得他支持3.0

我看你3天前提交的，我以为就支持，那还有没有其他方法游玩3.0GC呢？

**Comment by ErrorCodesForLzx** [comment]
> 为什么你觉得他支持3.0
那还有没有其他方法支持 3.0 安卓游玩呢

**Comment by 577fkj** [comment]
https://t.me/xfk233
