### ISSUE TITLE
what is the link of the official server?

### ISSUE THREAD

**Issue by pokemc32ryan** [577fkj/GenshinProxy#41]

**Comment by 577fkj** [comment]
what?

**Comment by pokemc32ryan** [comment]
![image](https://user-images.githubusercontent.com/87536022/187227484-9ad15705-2506-41ef-983e-a9b558c09c20.jpeg)
i mean this button's link is what?

**Comment by 577fkj** [comment]
> i mean this button's link is what?

No links

**Comment by pokemc32ryan** [comment]
ok
