### ISSUE TITLE
对3.1的支持

### ISSUE THREAD

**Issue by ZXAS007** [577fkj/GenshinProxy#45]
更新3.1了，能弹窗，能登录，但是会出现选择服务器页面，之后就就进官服了，账号效验失败

**Comment by ZXAS007** [comment]
额，你不会想等下一个版本更新前一星期发吧？

**Comment by hht805656153** [comment]
天真yc，不会下一个版本更新前一星期发，3.2版本出来后再更新3.1版本的，不过可以找作者customized。

**Comment by ZXAS007** [comment]
> 天真yc，不会下一个版本更新前一星期发，3.2版本出来后再更新3.1版本的，不过可以找作者customized。

好的，谢谢

**Comment by abu135a** [comment]
请问如何获得文件
