### ISSUE TITLE
强制代理问题

### ISSUE THREAD

**Issue by azzlantern** [577fkj/GenshinProxy#48]
![Screenshot_20221004-141116](https://user-images.githubusercontent.com/86811812/193807092-803283ef-8547-4c75-954e-c6d4a4a8ae56.png)
开了强制就这样了，大大知道怎么办嘛

**Comment by 577fkj** [comment]
不支持3.1

**Comment by Nall11** [comment]
..

**Comment by Nall11** [comment]
.......
