### ISSUE TITLE
App crash/force close

### ISSUE THREAD

**Issue by Neints** [577fkj/GenshinProxy#5]
First time open the app is working fine, but reopen it again cause the app crash/force close. (Tested using android 12)

**Comment by 577fkj** [comment]
I need a log

**Comment by Neints** [comment]
[crashlog.txt](https://github.com/577fkj/GenshinProxy/files/8838165/crashlog.txt)

**Comment by khaeruirgi** [comment]
yes that's right, this app also crashes on me (Redmi note 10 5G 8/128 Android 11)

**Comment by 577fkj** [comment]
After testing, the APK packaged by lspatch cannot be used. You need to use the manager to patch the version without built-in modules.

**Comment by 577fkj** [comment]
The latest version can be used normally
