### ISSUE TITLE
miui 13.0登陆开门后一直白屏 没有六国元素标志 过差不多10分钟后会显示链接中断

### ISSUE THREAD

**Issue by yonesone** [577fkj/GenshinProxy#6]

**Comment by 577fkj** [comment]
能否进入官服

**Comment by yonesone** [comment]
> 不能，点官服说我已经设置私服了

**Comment by 577fkj** [comment]
设置里开关全关了重启游戏进官服

**Comment by yonesone** [comment]
> 添加引号< Ctrl + Shift +．>❤️添加引号< Ctrl + Shift +．>❤️

什么意思 ，看不懂 sad

**Comment by yonesone** [comment]
> 什么意思呀 是在输入网址的时候＋引号吗？

**Comment by yonesone** [comment]
> 设置里开关全关了重启游戏进官服



> 设置里开关全关了重启游戏进官服

好我试试

**Comment by yonesone** [comment]
> 官方的进不去  显示数据异常

**Comment by yonesone** [comment]
> 设置里开关全关了重启游戏进官服

不行 什么都不设置 点官方 显示数据异常 错误码31-4303

**Comment by 577fkj** [comment]
> > 设置里开关全关了重启游戏进官服
> 
> 不行 什么都不设置 点官方 显示数据异常 错误码31-4303

白屏是你服务器游戏端口没开

**Comment by yonesone** [comment]
> > > 设置里开关全关了重启游戏进官服
> > 
> > 
> > 不行 什么都不设置 点官方 显示数据异常 错误码31-4303
> 
> 白屏是你服务器游戏端口没开

怎么开呀

**Comment by 577fkj** [comment]
> > > > 设置里开关全关了重启游戏进官服
> > > 
> > > 
> > > 不行 什么都不设置 点官方 显示数据异常 错误码31-4303
> > 
> > 
> > 白屏是你服务器游戏端口没开
> 
> 怎么开呀

自己去找教程，这里不教开服
