### ISSUE TITLE
从1.7更新到2.4后不弹窗了

### ISSUE THREAD

**Issue by JinShichang** [577fkj/GenshinProxy#7]
红米k20p MIUI12.5 安卓11 edxposed yahfa版本，之前用1.7是正常的，并且一开始也可以玩2.7，今天发现白屏玩不了（电脑能进）就更新了一下模块，然后就死活不弹窗了，游戏是play商店下载的

**Comment by duzhaokun123** [comment]
不兼容 edxposed

**Comment by JinShichang** [comment]
> 

但是1.7的时候是兼容的 而且作者也没说非得用什么xp

**Comment by 577fkj** [comment]
发日志

**Comment by JinShichang** [comment]
> 发日志

edxp获取不到日志，已经更换为zygisk+lsposed 问题解决 现在可以正常使用

**Comment by duzhaokun123** [comment]
> 但是1.7的时候是兼容的 而且作者也没说非得用什么xp

1.7 兼容因为当时没加载原生库
